### ISSUE TITLE
Users should not be able to book their own watches

### ISSUE THREAD

**Issue by Haumer** [KierynMo/WatchHunter#51]
![Screenshot 2021-06-02 at 15 02 24](https://user-images.githubusercontent.com/28539586/120494363-a8979200-c3b3-11eb-8bc3-4c3315898711.png)

so maybe on the `watches#index` action we can filter:
`
@watches = Watch.where.not(user: current_user)
`

and/or hide the booking form if `watch.user == current_user` !

what do you guys think? (low priority atm)

**Comment by tpmartin7** [comment]
I think it would be better to show your own watch in `watches#show`, otherwise you have no confirmation that the listing was successful. I'll disable the booking link, and maybe give an explanation when you hover over the booking button
